apiVersion: v1
kind: Pod
metadata:
  name: init-container-example
  labels:
    app: myapp
spec:
  initContainers:
    - name: sleepy
      image: harbor.dell.com/ai-accel-plat/imagecompliance/busybox:1.31.1
      command: ["sleep","30"]
  containers:
    - name: web
      image: harbor.dell.com/ai-accel-plat/imagecompliance/nginx:1.14.2