apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-demo
  labels:
    env: dev
  namespace: test-namespace
spec:
  containers:
    - name: test-liveness-probe
      image: harbor.dell.com/ai-accel-plat/imagecompliance/nginx:1.14.2
      ports:
        - containerPort: 80
          protocol: TCP
      livenessProbe:
        exec:
          command:
            - sh
            - -c
            - service nginx status | grep running
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 3 