apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    name: myapp
spec:
  volumes:
    - name: log
      emptyDir:
        {}
  containers:
  - name: busybox-container
    image: harbor.dell.com/ai-accel-plat/imagecompliance/busybox:1.31.1
    args:
      - /bin/sh
      - -c
      - >
        while true; do
          echo "$(date) INFO hello from main container" >> /var/log/myapp.log;
          sleep 1;
        done
    volumeMounts:
      - name: log
        mountPath: /var/log
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
        protocol: TCP
  - name: sidecar-busybox-container
    image: harbor.dell.com/ai-accel-plat/imagecompliance/busybox:1.31.1
    args:
      - /bin/sh
      - -c
      - tail -fn+1 /var/log/myapp.log
    volumeMounts:
      - name: log
        mountPath: /var/log
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
        protocol: TCP
