apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    type: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      type: dev
  template:
    metadata:
      labels:
        type: dev
    spec:
      containers:
        - name: nginx
          image: harbor.dell.com/ai-accel-plat/imagecompliance/nginx:1.14.2
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
    