apiVersion: v1
kind: Pod
metadata:
  name: test-images
spec:
  containers:
  - name: test-images
    image: harbor.dell.com/ai-accel/blueprints/test-docker:latest
    volumeMounts:
    - name: test-storage
      mountPath: /data/redis
  volumes:
  - name: test-storage
    emptyDir: {}

