apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp
    type: front-end
spec:
  containers:
    - name: nginx
      image: harbor.dell.com/ai-accel-plat/imagecompliance/nginx:1.14.2
