apiVersion: v1
kind: Service
metadata:
  name: sample-webapp-service
spec:
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30010
      protocol: TCP
  selector:
    app: webapp
    type: front-end
  type: NodePort